# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d63680a0d59544a97a168be47baa75a1d570696f57695a137de73176043b93b8e1fb0076d15a107d98bd323087e7657f0f793e8fe8c97732bf212f46a28ce192

test:
  secret_key_base: 974bb03e94e6bb0aebd19520ab923016d3a8bdaeab32c83fb935d6be963ba2e251911260a9d0d9530362f8198130eb593362ab75f6def59ba3f611b422304eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
